image: metasolutions/node-yarn:latest

options:
  max-time: 10

stepdefinitions:
  - build: &build
      name: Build
      script:
        - node --version
        - npm --version
        - yarn --version
        - yarn cache dir
        - export VERSION=`jq -r .version package.json` && echo $VERSION
        # We allow semantic versioning plus x.y-z (e.g. 4.10-SNAPSHOT which does not exactly conform to semver)
        - echo $VERSION | grep -P -q '^(0|[1-9]\d*)\.(0|[1-9]\d*)(\.*)(0*|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        - yarn
        - yarn build:all
        - ls -al dist/
        - if [ `wc -c < dist/rdforms.bmd.js` -gt 2000000 ]; then exit 1 ; fi
        - if [ `wc -c < dist/rdforms.bootstrap.js` -gt 2000000 ]; then exit 1 ; fi
        - if [ `wc -c < dist/rdforms.node.js` -gt 2000000 ]; then exit 1 ; fi

pipelines:
  default:
    - step: *build
