#!/usr/bin/env node

requirejs = require('requirejs');
requirejs.config({nodeRequire: require, baseUrl: '../../libs/', paths: {rdforms: ".."}});

if (process.argv.length < 3) {
    console.log("You need to call the program with one or three arguments like:");
    console.log("  $> ./rdfsGenerate skosInfile choicesOutfile instancesOfClass");
    console.log("    --OR--");
    console.log("  $> ./rdfsGenerate configFile");
    console.log("\nSee the test catalog for example config files.");
    process.exit();
}

var deps = ['fs', 'rdfjson/formats/converters', 'rdforms/converters/vocab/rdfs'];
if (process.argv.length === 3) {
    deps.push("rdforms/converters/vocab/"+process.argv[2]);
}

requirejs(deps, function (fs, converters, rdfs, conf) {
        if (process.argv.length > 4) {
            conf = {
                source: process.argv[2],
                destination: process.argv[3],
                instancesOfClass: process.argv[4]
            }
        }

        fs.readFile(conf.source, 'utf8', function(err, data) {
            var graph = converters.rdfxml2graph(data);
            var choices = rdfs.extractChoices(graph, conf);
            var fd = fs.openSync(conf.destination, "w");
            fs.writeSync(fd, JSON.stringify(choices, true, 1), 0, "utf8");
        });
    }
);